# Generated by Django 4.2.2 on 2023-06-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=10)),
                ('desc_automovil', models.TextField(max_length=500)),
                ('imagen_automovil', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('rut', models.AutoField(db_column='rut', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('ID_servicio', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='id')),
                ('Encargado', models.CharField(max_length=50, verbose_name='Encargado')),
                ('Tipo_de_Servicio', models.CharField(blank=True, max_length=90, null=True, verbose_name='Tipo_de_Servicio')),
                ('fecha_creacion', models.DateField(verbose_name='fecha_creacion')),
                ('imagen_automovil', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_rut_mecanico', models.ForeignKey(db_column='rut', on_delete=django.db.models.deletion.CASCADE, to='CasoRayoMakween.mecanico')),
            ],
            options={
                'ordering': ['ID_servicio'],
            },
        ),
    ]
