# Generated by Django 4.2.2 on 2023-07-01 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CasoRayoMakween', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'ordering': ['Encargado']},
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='id_rut_mecanico',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='imagen_automovil',
        ),
        migrations.AddField(
            model_name='mecanico',
            name='id_servicio',
            field=models.ForeignKey(db_column='id', default=2342, on_delete=django.db.models.deletion.CASCADE, to='CasoRayoMakween.servicios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicios',
            name='ID_servicio',
            field=models.AutoField(db_column='id', max_length=25, primary_key=True, serialize=False),
        ),
    ]
