# Generated by Django 4.2.2 on 2023-07-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CasoRayoMakween', '0002_alter_servicios_options_remove_mecanico_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='ID_servicio',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
